sudo: false
language: node_js
node_js:
  - "4.0"
  - "4.3"
  - "4"
  - "5.0"
  - "5"
  - "6"
  - "7"
env:
  - NPM_VERSION=4
  - NPM_VERSION=3
  - NPM_VERSION=2
addons:
  apt:
    packages:
    - imagemagick
script:
  - npm test
  - npm install . -g
  - ./runIntegrationTests.sh
before_install:
  - npm install -g npm@$NPM_VERSION
before_script:
  - npm install -g npm 
  - npm install -g cordova
